name: gh solar systems

on:
  push

jobs:
  display:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: display kubeconfig
      run: |
        echo ${{secrets.KUBECONFIG}}
        cat ${{secrets.KUBECONFIG}}